In [ ]:
import numpy as np

print("=== EJEMPLO 1: ANÁLISIS Y LIMPIEZA DE DATOS ESTUDIANTILES ===")

# 1. Simulación de datos: Matriz de 5 estudiantes x 4 materias (Notas de 0 a 10)
# Incluimos deliberadamente errores (notas negativas o mayores a 10) para validación
np.random.seed(42)
datos_brutos = np.array([
    [8.5,  9.0, -2.0,  7.5],  # Contiene un error (-2.0)
    [6.0,  5.5,  8.0,  6.5],
    [10.0, 11.5, 9.0,  9.5],  # Contiene un error (11.5)
    [4.0,  3.5,  5.0,  2.0],
    [7.0,  8.0,  8.5,  9.0]
])

print("\nMatriz Original (Datos Brutos):\n", datos_brutos)

# 2. VALIDACIÓN: Identificación e imputación de errores
# Regla: Las notas válidas deben estar en el rango [0.0, 10.0]
mascara_invalidos = (datos_brutos < 0) | (datos_brutos > 10)
print(f"\n¿Se detectaron errores en el registro?: {np.any(mascara_invalidos)}")

# Corrección: Reemplazar valores inválidos por la mediana de las notas válidas
datos_limpios = datos_brutos.copy()
promedio_valido = np.mean(datos_brutos[~mascara_invalidos])
datos_limpios[mascara_invalidos] = np.round(promedio_valido, 1)

print("\nMatriz Corregida (Datos Limpios):\n", datos_limpios)

# 3. PROCESAMIENTO VECTORIZADO: Estadísticas por estudiante y por materia
promedio_estudiantes = np.mean(datos_limpios, axis=1)  # Promedio por fila
promedio_materias = np.mean(datos_limpios, axis=0)     # Promedio por columna

# Condicional vectorial: Determinar si el estudiante aprueba (Nota >= 7.0)
estado_aprobacion = np.where(promedio_estudiantes >= 7.0, "APROBADO", "REPROBADO")

# 4. RESULTADOS
for i in range(len(promedio_estudiantes)):
    print(f"Estudiante {i+1}: Promedio = {promedio_estudiantes[i]:.2f} | Estado: {estado_aprobacion[i]}")

print("\nPromedio general por materia:", np.round(promedio_materias, 2))

=== EJEMPLO 1: ANÁLISIS Y LIMPIEZA DE DATOS ESTUDIANTILES ===

Matriz Original (Datos Brutos):
 [[ 8.5  9.  -2.   7.5]
 [ 6.   5.5  8.   6.5]
 [10.  11.5  9.   9.5]
 [ 4.   3.5  5.   2. ]
 [ 7.   8.   8.5  9. ]]

¿Se detectaron errores en el registro?: True

Matriz Corregida (Datos Limpios):
 [[ 8.5  9.   7.   7.5]
 [ 6.   5.5  8.   6.5]
 [10.   7.   9.   9.5]
 [ 4.   3.5  5.   2. ]
 [ 7.   8.   8.5  9. ]]
Estudiante 1: Promedio = 8.00 | Estado: APROBADO
Estudiante 2: Promedio = 6.50 | Estado: REPROBADO
Estudiante 3: Promedio = 8.88 | Estado: APROBADO
Estudiante 4: Promedio = 3.62 | Estado: REPROBADO
Estudiante 5: Promedio = 8.12 | Estado: APROBADO

Promedio general por materia: [7.1 6.6 7.5 6.9]


In [ ]:
import numpy as np

print("=== EJEMPLO 2: PROCESAMIENTO MATRICIAL DE IMÁGENES (RGB) ===")

# 1. Creación de una imagen sintética 4x4 píxeles RGB (Alto x Ancho x 3 Canales)
# Valores de color entre 0 y 255 (uint8)
np.random.seed(10)
imagen_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("\nDimensiones de la imagen (Alto, Ancho, Canales):", imagen_rgb.shape)
print("\nMatriz de Píxeles RGB Original (Muestra 2x2):\n", imagen_rgb[:2, :2, :])

# 2. ALGORITMO DE CONVERSIÓN A ESCALA DE GRISES (Ponderación Luma estándar)
# Fórmula: Grayscale = 0.299*R + 0.587*G + 0.114*B
pesos_rgb = np.array([0.299, 0.587, 0.114])

# Producto punto a lo largo del último eje (canales)
imagen_grises = np.dot(imagen_rgb, pesos_rgb).astype(np.uint8)

print("\nImagen transformada a Escala de Grises (4x4):\n", imagen_grises)

# 3. VALIDACIÓN Y AJUSTE DE CONTRASTE (Binarización/Umbralización)
# Regla: Si el valor de gris es > 128 el píxel pasa a blanco (255), de lo contrario a negro (0)
UMBRAL = 128
imagen_binaria = np.where(imagen_grises > UMBRAL, 255, 0)

print(f"\nImagen Binarizada (Umbral = {UMBRAL}):\n", imagen_binaria)
print(f"\nPorcentaje de píxeles activos (Blancos): {np.mean(imagen_binaria == 255) * 100:.1f}%")

=== EJEMPLO 2: PROCESAMIENTO MATRICIAL DE IMÁGENES (RGB) ===

Dimensiones de la imagen (Alto, Ancho, Canales): (4, 4, 3)

Matriz de Píxeles RGB Original (Muestra 2x2):
 [[[  9  69 117]
  [197 125 156]]

 [[ 15 114 157]
  [126  64 197]]]

Imagen transformada a Escala de Grises (4x4):
 [[ 56 150 107 123]
 [ 89  97 124 107]
 [148 152 223 118]
 [161 193  93 116]]

Imagen Binarizada (Umbral = 128):
 [[  0 255   0   0]
 [  0   0   0   0]
 [255 255 255   0]
 [255 255   0   0]]

Porcentaje de píxeles activos (Blancos): 37.5%
